print("          *          ")
print("        * * *         ")
print("    * * * * * * *     ")
print("        * * *         ")
print("      * * * * *       ")
print("* " *11)
print("        *   *      ")
print("        *   *      ")
